apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DEFAULT_URI: https://staging.example.com
  # Override email recipients in staging to prevent sending to real users.
  MAILER_OVERRIDE_RECIPIENTS: "dev@example.com"
