apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  APP_SECRET: change-me
  DATABASE_URL: "postgresql://user:pass@app-postgres:5432/dbname?serverVersion=16&charset=utf8"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-postgres-secret
type: Opaque
stringData:
  username: change-me
  password: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: app-staging-basic-auth
type: Opaque
stringData:
  users: "user:$2y$05$hashed-here"
